

DATABASE_CONFIG_KEY = "DATABASE_CONFIG"

GREENHOUSE_POLLING_CONFIG_KEY = "GREENHOUSE_POLLING_CONFIG"

OPENAI_API_KEY = "OPENAI_API_KEY"

TELEGRAM_API_KEY = "TELEGRAM_API_KEY"

EMBEDDING_MODEL_MAX_CONCURRENT_CALLS = "EMBEDDING_MODEL_MAX_CONCURRENT_CALLS"

CALL_LLM_MAX_CONCURRENT_CALLS = "CALL_LLM_MAX_CONCURRENT_CALLS"

CALL_LLM_RETRY_COUNT = "CALL_LLM_RETRY_COUNT"

CALL_LLM_INSTRUCTOR_RETRY_COUNT = "CALL_LLM_INSTRUCTOR_RETRY_COUNT"

SAME_COMPANY_POLLING_GAP_IN_SECONDS = "SAME_COMPANY_POLLING_GAP_IN_SECONDS"

JOB_RETENTION_PERIOD_IN_DAYS = "JOB_RETENTION_PERIOD_IN_DAYS"

COMPANY_BATCH_SIZE_FOR_POLLING = "COMPANY_BATCH_SIZE_FOR_POLLING"

SIMILARITY_THRESHOLD_FOR_VECTOR_SEARCH = "SIMILARITY_THRESHOLD_FOR_VECTOR_SEARCH" # should be in [0,1]

JOB_PROCESSING_BATCH_SIZE = "JOB_PROCESSING_BATCH_SIZE"